"""XPolicyLab-compatible model wrapper for GPT-Policy.

This module is intentionally policy-server side: RoboDojo owns physics and
success evaluation, while GPT-Policy owns one closed-loop VLM decision at a
time. It can be imported by a small XPolicyLab policy package generated by the
bootstrap script.
"""

from __future__ import annotations

import io
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

import numpy as np
from PIL import Image

from ..harness.config import agent_config
from ..harness.contract import AgentSession
from ..harness.factory import create_agent
from ..harness.models import AgentContext, AgentTurn
from ..harness.protocol import instructions, observation, output_schema, tool_schemas
from ..settings import load_settings
from ..tools import load_tool_catalog
from .adapter import RoboDojoAdapter
from .calibration import RoboDojoCalibration


@dataclass(frozen=True)
class _Image:
    name: str
    data: bytes
    mime_type: str
    width: int
    height: int
    rgb_data: bytes | None = None

    def data_url(self) -> str:
        import base64
        return f"data:{self.mime_type};base64,{base64.b64encode(self.data).decode('ascii')}"


def _image(name: str, value: Any, quality: int = 85) -> _Image:
    array = np.asarray(value)
    if array.ndim != 3 or array.shape[2] not in (3, 4):
        raise ValueError(f"camera {name} color must be HxWx3/4, got {array.shape}")
    rgb = np.ascontiguousarray(array[:, :, :3].astype(np.uint8))
    output = io.BytesIO()
    Image.fromarray(rgb, mode="RGB").save(output, format="JPEG", quality=quality)
    height, width = rgb.shape[:2]
    return _Image(name, output.getvalue(), "image/jpeg", width, height, rgb.tobytes())


def _jsonable(value: Any) -> Any:
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, dict):
        return {str(k): _jsonable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(v) for v in value]
    if isinstance(value, (np.integer, np.floating)):
        return value.item()
    return value


class GPTPolicyModel:
    """ModelTemplate-shaped class without importing XPolicyLab at import time."""

    def __init__(self, model_cfg: Mapping[str, Any]):
        config_path = Path(str(model_cfg["gpt_policy_config"])).expanduser().resolve()
        settings = load_settings(config_path)
        settings["backend"] = "robodojo"
        self.settings = settings
        self.model_cfg = dict(model_cfg)
        self.robot_model = str(model_cfg.get("robot_model", "X5"))
        self.arms = tuple(model_cfg.get("arms", ("left", "right")))
        calibration_path = Path(str(model_cfg["calibration_manifest"])).expanduser().resolve()
        manifest = json.loads(calibration_path.read_text(encoding="utf-8"))
        self._calibration_manifest = manifest
        self.adapter = RoboDojoAdapter(
            RoboDojoCalibration.from_manifest(manifest), self.arms, self.robot_model
        )
        self.catalog = load_tool_catalog(settings)
        self.agent_cfg = agent_config(settings, config_path.parent)
        self.agent: AgentSession = create_agent(self.agent_cfg, model_cfg.get("model") or self.agent_cfg.model or "gpt-6-astra", True, 85)
        self.previous: str | None = None
        self.latest_frame: Mapping[str, Any] | None = None
        self.latest_state: dict[str, Any] | None = None
        self.latest_images: dict[str, _Image] = {}
        self.step = 0
        self._started = False

    def _start(self, instruction: str) -> None:
        dof = int(self.model_cfg.get("dof", 6))
        schema = output_schema(dof, self.arms, self.catalog)
        tools = tool_schemas(dof, self.arms, self.catalog)
        prompt = instructions(self.robot_model, "robodojo", dof, self.arms, self.settings, self.catalog, task_instruction=instruction)
        self.agent.start(AgentContext(prompt, tools, schema))
        self._started = True

    def reset(self):
        if self._started:
            self.agent.close()
        self.previous = None
        self.latest_frame = None
        self.latest_state = None
        self.latest_images = {}
        self.step = 0
        self._started = False

    def update_obs(self, obs: Mapping[str, Any]):
        self.latest_frame = obs
        # RoboDojo emits the active camera matrices when the env overlay has
        # intrinsic_matrix/extrinsic_matrix enabled. Merge those matrices into
        # the same calibration object used for state and context metadata so
        # the model never sees raw camera geometry without its semantic
        # calibration summary.
        self.adapter.calibration = RoboDojoCalibration.from_observation(
            self._calibration_manifest, obs
        )
        self.latest_state = self.adapter.state(obs)
        self.latest_images = {
            str(name): _image(str(name), data["color"])
            for name, data in (obs.get("vision") or {}).items()
            if isinstance(data, Mapping) and data.get("color") is not None
        }
        if not self._started:
            instruction = str(obs.get("instruction") or self.model_cfg.get("task_name") or "Complete the RoboDojo task.")
            self._start(instruction)

    def update_obs_batch(self, obs_list):
        if len(obs_list) != 1:
            raise NotImplementedError("GPT-Policy closed-loop VLM mode currently requires eval_batch=false")
        self.update_obs(obs_list[0])

    def get_action(self):
        if self.latest_frame is None or self.latest_state is None or not self._started:
            raise RuntimeError("update_obs must be called before get_action")
        camera_meta = []
        for name, data in (self.latest_frame.get("vision") or {}).items():
            if not isinstance(data, Mapping):
                continue
            camera_meta.append(_jsonable({key: value for key, value in data.items() if key != "color"} | {"name": name}))
        text = observation(
            str(self.latest_frame.get("instruction") or self.model_cfg.get("task_name") or "Complete the RoboDojo task."),
            self.latest_state,
            camera_meta,
            self.previous,
            self.step,
            self.adapter.observation_metadata(self.latest_frame, self.step),
        )
        decision = self.agent.decide(AgentTurn(text, self.latest_images))
        self.step += 1
        name, arguments = str(decision.get("name")), decision.get("arguments", {})
        if name in {"terminal.done", "terminal.give_up"}:
            return [self._hold_action()]
        if name in {"locate_point", "check_path"}:
            # These GPT-Policy tools are analytical/read-only. RoboDojo does
            # not expose a separate tool-call channel, so preserve the
            # simulator state for this cycle and let the next observation
            # provide the result (all raw camera/calibration fields remain in
            # the context).
            return [self._hold_action()]
        if name == "move_eef_chunk":
            actions = [self.adapter.action({"target": point}) for point in arguments.get("poses", [])]
        elif name in {"move_to", "set_gripper"}:
            actions = [self.adapter.action(arguments)]
        else:
            raise ValueError(f"RoboDojo cannot execute GPT-Policy tool {name!r} directly")
        # XPolicyLab's bimanual action contract requires a gripper field for
        # every arm on every waypoint, even when the selected GPT-Policy tool
        # only changes TCP pose. Hold the simulator's measured gripper values
        # explicitly so no information is silently invented or omitted.
        state = self.latest_frame.get("state", {})
        for action in actions:
            for arm in self.arms:
                prefix = f"{arm}_" if len(self.arms) > 1 else ""
                grip_key = f"{prefix}ee_joint_state"
                if grip_key not in action and grip_key in state:
                    action[grip_key] = _jsonable(state[grip_key])
        self.previous = json.dumps({"tool": name, "result": {"accepted": True}}, ensure_ascii=False)
        return actions

    def get_action_batch(self, env_idx_list=None):
        if env_idx_list not in (None, [0]):
            raise NotImplementedError("GPT-Policy VLM mode currently requires one environment")
        return [self.get_action()]

    def _hold_action(self):
        assert self.latest_frame is not None
        state = self.latest_frame.get("state", {})
        action = {}
        for arm in self.arms:
            prefix = f"{arm}_" if len(self.arms) > 1 else ""
            action[f"{prefix}ee_pose"] = state[f"{prefix}ee_pose"]
            action[f"{prefix}ee_joint_state"] = state.get(f"{prefix}ee_joint_state", [0.0])
        return action
