"""XPolicyLab-compatible model wrapper for GPT-Policy.

This module is intentionally policy-server side: RoboDojo owns physics and
success evaluation, while GPT-Policy owns one closed-loop VLM decision at a
time. It can be imported by a small XPolicyLab policy package generated by the
bootstrap script.
"""

from __future__ import annotations

import io
import json
import os
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

import numpy as np
from PIL import Image

from ..harness.config import agent_config
from ..harness.contract import AgentSession
from ..harness.factory import create_agent
from ..harness.errors import AgentOverloadedError
from ..harness.models import AgentContext, AgentTurn
from ..harness.protocol import instructions, observation, output_schema, tool_schemas
from ..settings import load_settings
from ..tools import load_tool_catalog
from .adapter import RoboDojoAdapter
from .calibration import RoboDojoCalibration


@dataclass(frozen=True)
class _Image:
    name: str
    data: bytes
    mime_type: str
    width: int
    height: int
    rgb_data: bytes | None = None

    def data_url(self) -> str:
        import base64
        return f"data:{self.mime_type};base64,{base64.b64encode(self.data).decode('ascii')}"


def _image(name: str, value: Any, quality: int = 85) -> _Image:
    array = np.asarray(value)
    if array.ndim != 3 or array.shape[2] not in (3, 4):
        raise ValueError(f"camera {name} color must be HxWx3/4, got {array.shape}")
    rgb = np.ascontiguousarray(array[:, :, :3].astype(np.uint8))
    output = io.BytesIO()
    Image.fromarray(rgb, mode="RGB").save(output, format="JPEG", quality=quality)
    height, width = rgb.shape[:2]
    return _Image(name, output.getvalue(), "image/jpeg", width, height, rgb.tobytes())


def _jsonable(value: Any) -> Any:
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, dict):
        return {str(k): _jsonable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(v) for v in value]
    if isinstance(value, (np.integer, np.floating)):
        return value.item()
    return value


def _canonical_tool_name(name: str) -> str:
    """Accept both GPT tool aliases and the namespaced protocol names."""
    return {"done": "terminal.done", "give_up": "terminal.give_up"}.get(name, name)


class GPTPolicyModel:
    """ModelTemplate-shaped class without importing XPolicyLab at import time."""

    def __init__(self, model_cfg: Mapping[str, Any]):
        config_path = Path(str(model_cfg["gpt_policy_config"])).expanduser().resolve()
        settings = load_settings(config_path)
        settings["backend"] = "robodojo"
        self.settings = settings
        self.model_cfg = dict(model_cfg)
        self.robot_model = str(model_cfg.get("robot_model", "X5"))
        self.arms = tuple(model_cfg.get("arms", ("left", "right")))
        calibration_path = Path(str(model_cfg["calibration_manifest"])).expanduser().resolve()
        manifest = json.loads(calibration_path.read_text(encoding="utf-8"))
        self._calibration_manifest = manifest
        self.adapter = RoboDojoAdapter(
            RoboDojoCalibration.from_manifest(manifest), self.arms, self.robot_model
        )
        self.catalog = load_tool_catalog(settings)
        self.agent_cfg = agent_config(settings, config_path.parent)
        self._agent_model = model_cfg.get("model") or self.agent_cfg.model or "gpt-6-astra"
        self.agent: AgentSession = create_agent(self.agent_cfg, self._agent_model, True, 85)
        self.previous: str | None = None
        self.latest_frame: Mapping[str, Any] | None = None
        self.latest_state: dict[str, Any] | None = None
        self.latest_images: dict[str, _Image] = {}
        self.step = 0
        self._started = False
        # RoboDojo runs this wrapper in a long-lived policy server, outside
        # the normal hardware runner that owns RunRecorder. Keep an equivalent
        # lightweight trace here so every simulator turn has durable JSONL
        # evidence and camera frames.
        default_trace_root = Path(__file__).resolve().parents[3] / "var/runs/gpt/robodojo"
        trace_root = Path(str(model_cfg.get("trace_dir") or default_trace_root)).expanduser()
        trace_root.mkdir(parents=True, exist_ok=True)
        run_name = f"{time.strftime('%Y%m%d-%H%M%S')}-{time.time_ns() % 1_000_000:06d}-push_T-pid{os.getpid()}"
        self.trace_dir = trace_root / run_name
        self.trace_dir.mkdir(parents=True, exist_ok=False)
        self.trace_frames = self.trace_dir / "frames"
        self.trace_frames.mkdir()
        self.trace_events = (self.trace_dir / "events.jsonl").open("a", encoding="utf-8")
        self._trace_event("run_started", {"model": self._agent_model, "robot_model": self.robot_model, "arms": self.arms})

    def _start(self, instruction: str) -> None:
        dof = int(self.model_cfg.get("dof", 6))
        schema = output_schema(dof, self.arms, self.catalog)
        tools = tool_schemas(dof, self.arms, self.catalog)
        prompt = instructions(self.robot_model, "robodojo", dof, self.arms, self.settings, self.catalog, task_instruction=instruction)
        self.agent.start(AgentContext(prompt, tools, schema))
        self._started = True

    def reset(self):
        if self._started:
            self.agent.close()
        # A Codex app-server session is single-use after close(). RoboDojo
        # may reset and reuse the same policy object across seeds, so create a
        # fresh session instead of sending requests to the closed process.
        self.agent = create_agent(self.agent_cfg, self._agent_model, True, 85)
        self.previous = None
        self.latest_frame = None
        self.latest_state = None
        self.latest_images = {}
        self.step = 0
        self._started = False
        self._trace_event("reset", {})

    def update_obs(self, obs: Mapping[str, Any]):
        self.latest_frame = obs
        # RoboDojo emits the active camera matrices when the env overlay has
        # intrinsic_matrix/extrinsic_matrix enabled. Merge those matrices into
        # the same calibration object used for state and context metadata so
        # the model never sees raw camera geometry without its semantic
        # calibration summary.
        self.adapter.calibration = RoboDojoCalibration.from_observation(
            self._calibration_manifest, obs
        )
        self.latest_state = self.adapter.state(obs)
        self.latest_images = {
            str(name): _image(str(name), data["color"])
            for name, data in (obs.get("vision") or {}).items()
            if isinstance(data, Mapping) and data.get("color") is not None
        }
        self._trace_observation(obs)
        if not self._started:
            instruction = str(obs.get("instruction") or self.model_cfg.get("task_name") or "Complete the RoboDojo task.")
            self._start(instruction)

    def update_obs_batch(self, obs_list):
        if len(obs_list) != 1:
            raise NotImplementedError("GPT-Policy closed-loop VLM mode currently requires eval_batch=false")
        self.update_obs(obs_list[0])

    def get_action(self):
        if self.latest_frame is None or self.latest_state is None or not self._started:
            raise RuntimeError("update_obs must be called before get_action")
        camera_meta = []
        for name, data in (self.latest_frame.get("vision") or {}).items():
            if not isinstance(data, Mapping):
                continue
            camera_meta.append(_jsonable({key: value for key, value in data.items() if key != "color"} | {"name": name}))
        text = observation(
            str(self.latest_frame.get("instruction") or self.model_cfg.get("task_name") or "Complete the RoboDojo task."),
            self.latest_state,
            camera_meta,
            self.previous,
            self.step,
            self.adapter.observation_metadata(self.latest_frame, self.step),
        )
        turn = AgentTurn(text, self.latest_images)
        decision = None
        for attempt in range(5):
            try:
                decision = self.agent.decide(turn)
                break
            except AgentOverloadedError:
                if attempt == 4:
                    raise
                # Astra capacity errors are transient. Keep the same thread
                # and request, with bounded backoff, instead of aborting a
                # simulator episode and losing its observations.
                time.sleep(2.0 * (attempt + 1))
        assert decision is not None
        self.step += 1
        name, arguments = str(decision.get("name")), decision.get("arguments", {})
        # The model may emit the canonical tool names without the namespace.
        # Treat both spellings identically at this integration boundary.
        canonical_name = _canonical_tool_name(name)
        self._trace_event("model_decision", {
            "step": self.step, "name": name, "canonical_name": canonical_name,
            "arguments": _jsonable(arguments), "state": _jsonable(self.latest_state),
        })
        if canonical_name in {"terminal.done", "terminal.give_up"}:
            self._trace_event("action", {"step": self.step, "name": canonical_name, "actions": self._hold_action()})
            return [self._hold_action()]
        if canonical_name in {"locate_point", "check_path"}:
            # These GPT-Policy tools are analytical/read-only. RoboDojo does
            # not expose a separate tool-call channel, so preserve the
            # simulator state for this cycle and let the next observation
            # provide the result (all raw camera/calibration fields remain in
            # the context).
            actions = [self._hold_action()]
        elif canonical_name == "move_eef_chunk":
            actions = [self.adapter.action({"target": point}) for point in arguments.get("poses", [])]
        elif canonical_name in {"move_to", "set_gripper"}:
            # A null gripper target is an explicit hold request. If every
            # selected side is null, emit a complete measured-state hold
            # action instead of asking the adapter to build an empty dict.
            positions = arguments.get("positions") if canonical_name == "set_gripper" else None
            single_hold = canonical_name == "set_gripper" and arguments.get("gripper") is None
            all_hold = isinstance(positions, Mapping) and all(
                positions.get(arm) is None for arm in self.arms
            )
            actions = [self._hold_action()] if single_hold or all_hold else [self.adapter.action(arguments)]
        else:
            error = ValueError(f"RoboDojo cannot execute GPT-Policy tool {name!r} directly")
            self._trace_event("error", {"step": self.step, "error": str(error), "name": name})
            raise error
        # XPolicyLab's bimanual action contract requires a gripper field for
        # every arm on every waypoint, even when the selected GPT-Policy tool
        # only changes TCP pose. Hold the simulator's measured gripper values
        # explicitly so no information is silently invented or omitted.
        state = self.latest_frame.get("state", {})
        for action in actions:
            for arm in self.arms:
                prefix = f"{arm}_" if len(self.arms) > 1 else ""
                pose_key = f"{prefix}ee_pose"
                if pose_key not in action and pose_key in state:
                    action[pose_key] = _jsonable(state[pose_key])
                grip_key = f"{prefix}ee_joint_state"
                if grip_key not in action and grip_key in state:
                    action[grip_key] = _jsonable(state[grip_key])
        self.previous = json.dumps({"tool": canonical_name, "result": {"accepted": True}}, ensure_ascii=False)
        self._trace_event("action", {"step": self.step, "name": canonical_name, "actions": _jsonable(actions)})
        return actions

    def get_action_batch(self, env_idx_list=None):
        if env_idx_list not in (None, [0]):
            raise NotImplementedError("GPT-Policy VLM mode currently requires one environment")
        return [self.get_action()]

    def _hold_action(self):
        assert self.latest_frame is not None
        state = self.latest_frame.get("state", {})
        action = {}
        for arm in self.arms:
            prefix = f"{arm}_" if len(self.arms) > 1 else ""
            action[f"{prefix}ee_pose"] = state[f"{prefix}ee_pose"]
            action[f"{prefix}ee_joint_state"] = state.get(f"{prefix}ee_joint_state", [0.0])
        return action

    def _trace_event(self, event: str, payload: Mapping[str, Any]) -> None:
        record = {"at": time.time(), "event": event, **_jsonable(dict(payload))}
        self.trace_events.write(json.dumps(record, ensure_ascii=False, default=str) + "\n")
        self.trace_events.flush()

    def _trace_observation(self, frame: Mapping[str, Any]) -> None:
        images = []
        for name, image in self.latest_images.items():
            path = self.trace_frames / f"step-{self.step:05d}-{name.replace('/', '_')}.jpg"
            path.write_bytes(image.data)
            images.append({"name": name, "path": str(path.relative_to(self.trace_dir)),
                           "width": image.width, "height": image.height,
                           "mime_type": image.mime_type})
        camera_metadata = []
        for name, data in (frame.get("vision") or {}).items():
            if isinstance(data, Mapping):
                camera_metadata.append(_jsonable({key: value for key, value in data.items()
                                                  if key != "color"} | {"name": name}))
        self._trace_event("observation", {
            "step": self.step, "instruction": frame.get("instruction"),
            "state": _jsonable(self.latest_state), "images": images,
            "camera_metadata": camera_metadata,
            "success": frame.get("success"), "end_flag": frame.get("end_flag"),
            "action_feedback": _jsonable(frame.get("action")),
        })
